"""
================================================================================
thesis_irf_figures.py
================================================================================
Thesis:  "When Rates Hit Zero: Identifying Monetary Shocks with Shadow Rates"
Author:  Burak Tanir
Date:    April 2026

Purpose
-------
Produces the three main IRF figures reported in the thesis by reading the
pre-saved IRF CSV tables generated by bvar_irf_estimation.py. No
re-estimation is performed — this script is purely a plotting tool that
applies consistent thesis-ready formatting to the saved results.

The three figures correspond directly to the results discussion in
Sections 5 and 7 of the thesis:

    Figure 1 — Pre-2008: AD vs FFR
        Compares the original Aruoba-Drechsel (2024) shock series with the
        replicated FFR-based shock series in the pre-2008 (conventional
        policy) period. Validates the replication by showing that both
        series produce near-identical impulse responses across all six
        macroeconomic variables.

    Figure 2 — Post-2008: Wu-Xia only
        Shows the impulse responses to the Wu-Xia shadow rate shock in the
        post-2008 (zero lower bound) period. This is the main result for
        the unconventional policy era.

    Figure 3 — Cross-regime: Pre-2008 FFR vs Post-2008 Wu-Xia
        Overlays the pre-2008 FFR responses and the post-2008 Wu-Xia
        responses in the same panels, enabling a direct cross-regime
        comparison of monetary transmission patterns.

Notes on labelling
------------------
    The Hybrid shock series (produced by ridge regression on FFR changes)
    is displayed as "FFR" throughout all figures. This is correct because
    the Hybrid series IS the FFR-based shock — "Hybrid" is an internal
    code label reflecting its construction method, whereas "FFR" is the
    economically meaningful label for the thesis reader.

Variable ordering in figures
-----------------------------
    All figures display variables in the following fixed order:
        1. y1         — 1-year Treasury yield
        2. log_sp500  — S&P 500 index (log)
        3. log_rgdp   — Real GDP (log)
        4. unemp      — Unemployment rate
        5. log_pgdp   — GDP deflator (log)
        6. EBP        — Excess bond premium

    This order is applied consistently across all three figures so that
    the same variable always appears in the same panel position.

Input
-----
    irf_outputs_EBP_final/
        IRF CSV tables produced by bvar_irf_estimation.py. Files are
        located by regex pattern matching so exact p and H values in the
        filename do not need to be hardcoded:
            Table_IRF_AruobaDrechsel_Pre2008_p{p}_H{H}_EBP.csv
            Table_IRF_Hybrid_Pre2008_p{p}_H{H}_EBP.csv
            Table_IRF_WuXia_Post2008_p{p}_H{H}_EBP.csv

Output
------
    irf_outputs_EBP_final/thesis_figures_from_csv/
        Figure_Pre2008_Compare_AD_vs_FFR.png
        Figure_Post2008_IRF_WuXia.png
        Figure_CrossRegime_Compare_PreFFR_vs_PostWuXia.png

    All figures saved at 300 dpi with tight bounding boxes.

Dependencies
------------
    os, re  (standard library)
    numpy, pandas, matplotlib  — pip install numpy pandas matplotlib

Usage
-----
    python thesis_irf_figures.py

    Must be run after bvar_irf_estimation.py has produced the IRF CSV
    tables. Run from the same working directory as the estimation script.
================================================================================
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# SECTION 1 — PATH CONFIGURATION
# ============================================================
# All paths are resolved relative to the current working directory.
# IRF CSV tables are read from irf_outputs_EBP_final/ (produced by
# bvar_irf_estimation.py). Thesis figures are saved to a dedicated
# subfolder to keep them separate from the estimation outputs.

BASE_DIR = os.getcwd()

# Folder containing the IRF CSV tables from bvar_irf_estimation.py
IRF_DIR = os.path.join(BASE_DIR, "irf_outputs_EBP_final")

# Output folder for thesis-ready figures
OUTDIR  = os.path.join(IRF_DIR, "thesis_figures_from_csv")
os.makedirs(OUTDIR, exist_ok=True)


# ============================================================
# SECTION 2 — DISPLAY SETTINGS
# ============================================================
# Y-axis labels match the units used in the BVAR estimation.
# DISPLAY_LABELS maps internal column names to thesis-ready axis labels.
# Variables appear in the figures in the order they are stored in the IRF
# CSV files, which matches the macro_vars order in bvar_irf_estimation.py.

DISPLAY_LABELS = {
    "y1":        "1Y Gov Bond (%)",
    "log_sp500": "S&P500 (100 × log)",
    "log_rgdp":  "Real GDP (100 × log)",
    "unemp":     "Unemployment (%)",
    "log_pgdp":  "GDP Deflator (100 × log)",
    "EBP":       "EBP (%)",
}



# Fixed variable order for all thesis figures — matches macro_vars
# in bvar_irf_estimation.py exactly.
PREFERRED_ORDER = ["y1", "log_sp500", "log_rgdp", "unemp", "log_pgdp", "EBP"]


def pretty_ylabel(varname: str) -> str:
    """Return the thesis-standard y-axis label for a BVAR variable."""
    return DISPLAY_LABELS.get(varname, varname)


# ============================================================
# SECTION 3 — FILE HELPER FUNCTIONS
# ============================================================

def find_first(pattern: str) -> str:
    """
    Find the first file in IRF_DIR whose name fully matches a regex pattern.

    Using regex matching rather than exact filenames makes the script
    robust to changes in the p (lag order) and H (horizon) values baked
    into the CSV filenames by bvar_irf_estimation.py. The first
    alphabetically sorted match is returned.

    Parameters
    ----------
    pattern : str  Regex pattern to match against filenames in IRF_DIR.
                   Must be a full-match pattern (anchored at both ends).

    Returns
    -------
    str  Absolute path to the matched file.

    Raises
    ------
    FileNotFoundError  If no file in IRF_DIR matches the pattern.
    """
    rx = re.compile(pattern)
    for fn in sorted(os.listdir(IRF_DIR)):
        if rx.fullmatch(fn):
            return os.path.join(IRF_DIR, fn)
    raise FileNotFoundError(
        f"Could not find a file matching:\n  {pattern}\nIn:\n  {IRF_DIR}"
    )


def read_irf_csv(path: str):
    """
    Read a saved IRF CSV table and return arrays ready for plotting.

    The CSV format produced by bvar_irf_estimation.py has columns:
        h                — horizon index (0, 1, ..., H)
        {var}_med        — posterior median IRF
        {var}_lo         — lower credible band (16th percentile)
        {var}_hi         — upper credible band (84th percentile)

    Variables are returned in the order they appear in the CSV,
    which matches the macro_vars ordering in bvar_irf_estimation.py.

    Parameters
    ----------
    path : str  Absolute path to the IRF CSV file.

    Returns
    -------
    h       : np.ndarray   Horizon array (H+1,).
    ordered : list of str  Variable names in CSV column order.
    med     : dict         {var: np.ndarray} posterior medians.
    lo      : dict         {var: np.ndarray} lower credible bands.
    hi      : dict         {var: np.ndarray} upper credible bands.

    Raises
    ------
    ValueError  If the 'h' column or any required _med/_lo/_hi column
                is missing from the CSV.
    """
    df = pd.read_csv(path)
    if "h" not in df.columns:
        raise ValueError(
            f"'h' column missing in {path}. Columns: {list(df.columns)}"
        )

    h = df["h"].to_numpy()

    # Identify variables from columns ending with _med
    vars_found = []
    for c in df.columns:
        if c.endswith("_med"):
            vars_found.append(c[:-4])
    vars_found = sorted(set(vars_found))

    # Apply PREFERRED_ORDER; append any extra variables not in the list
    ordered = [v for v in PREFERRED_ORDER if v in vars_found] + \
              [v for v in vars_found if v not in PREFERRED_ORDER]

    med, lo, hi = {}, {}, {}
    for v in ordered:
        for suf in ["_med", "_lo", "_hi"]:
            col = v + suf
            if col not in df.columns:
                raise ValueError(f"Missing column '{col}' in {path}.")
        med[v] = df[v + "_med"].to_numpy()
        lo[v]  = df[v + "_lo"].to_numpy()
        hi[v]  = df[v + "_hi"].to_numpy()

    return h, ordered, med, lo, hi


# ============================================================
# SECTION 4 — PLOTTING FUNCTIONS
# ============================================================

def plot_overlay_two_shocks(h, vars_list, A, B, labelA, labelB, title, out_png):
    """
    Plot two IRF sets in the same panels for direct comparison.

    Displays posterior median lines for both series with 68% credible
    bands (20% opacity). Series A is plotted as a solid line; series B
    as a dashed line. Used for:
        - Figure 1: AD vs FFR (pre-2008 replication validation)
        - Figure 3: Pre-2008 FFR vs Post-2008 Wu-Xia (cross-regime)

    Variables are arranged in a two-column grid in the order given by
    vars_list, which follows the macro_vars ordering from bvar_irf_estimation.py.

    Parameters
    ----------
    h         : np.ndarray   Horizon array.
    vars_list : list of str  Variables to plot (in CSV order).
    A, B      : tuple        (med_dict, lo_dict, hi_dict) for each series.
    labelA    : str          Legend label for series A (solid line).
    labelB    : str          Legend label for series B (dashed line).
    title     : str          Figure suptitle.
    out_png   : str          Output PNG file path.
    """
    medA, loA, hiA = A
    medB, loB, hiB = B

    n     = len(vars_list)
    nrows = int(np.ceil(n / 2))
    fig, axes = plt.subplots(nrows, 2, figsize=(12, 4 * nrows), sharex=True)
    axes = np.array(axes).reshape(-1)

    SCALE_BY_100 = ["log_sp500", "log_rgdp", "log_pgdp"]

    for i, v in enumerate(vars_list):
        ax   = axes[i]
        sc   = 100.0 if v in SCALE_BY_100 else 1.0
        ax.plot(h, sc * medA[v], linewidth=2, label=labelA)
        ax.fill_between(h, sc * loA[v], sc * hiA[v], alpha=0.20)
        ax.plot(h, sc * medB[v], linewidth=2, linestyle="--", label=labelB)
        ax.fill_between(h, sc * loB[v], sc * hiB[v], alpha=0.20)
        ax.axhline(0, linewidth=1)
        ax.set_ylabel(pretty_ylabel(v))
        ax.grid(True)
        ax.legend()

    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(title, y=1.02, fontsize=14)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.show()
    print(f"Saved: {out_png}")


def plot_single_shock(h, vars_list, med, lo, hi, title, out_png):
    """
    Plot IRFs for a single shock series across all variables.

    Displays the posterior median with a 68% credible band (25% opacity).
    Used for Figure 2 (Post-2008 Wu-Xia only).

    Variables are arranged in a two-column grid in the order given by
    vars_list, which follows the macro_vars ordering from bvar_irf_estimation.py.

    Parameters
    ----------
    h         : np.ndarray   Horizon array.
    vars_list : list of str  Variables to plot (in CSV order).
    med       : dict         {var: np.ndarray} posterior medians.
    lo        : dict         {var: np.ndarray} lower credible bands.
    hi        : dict         {var: np.ndarray} upper credible bands.
    title     : str          Figure suptitle.
    out_png   : str          Output PNG file path.
    """
    n     = len(vars_list)
    nrows = int(np.ceil(n / 2))
    fig, axes = plt.subplots(nrows, 2, figsize=(12, 4 * nrows), sharex=True)
    axes = np.array(axes).reshape(-1)

    SCALE_BY_100 = ["log_sp500", "log_rgdp", "log_pgdp"]

    for i, v in enumerate(vars_list):
        ax  = axes[i]
        sc  = 100.0 if v in SCALE_BY_100 else 1.0
        ax.plot(h, sc * med[v], linewidth=2)
        ax.fill_between(h, sc * lo[v], sc * hi[v], alpha=0.25)
        ax.axhline(0, linewidth=1)
        ax.set_ylabel(pretty_ylabel(v))
        ax.grid(True)

    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(title, y=1.02, fontsize=14)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.show()
    print(f"Saved: {out_png}")


# ============================================================
# SECTION 5 — MAIN EXECUTION
# ============================================================

def main():
    """
    Main execution function: locate CSVs, read IRFs, and produce figures.

    Execution order:
        1. Locate the three required IRF CSV files by regex pattern
        2. Read each CSV into horizon arrays and IRF dictionaries
        3. Compute variable intersections for overlay figures
        4. Warn if horizon arrays differ between series
        5. Produce Figure 1: Pre-2008 AD vs FFR
        6. Produce Figure 2: Post-2008 Wu-Xia only
        7. Produce Figure 3: Cross-regime FFR vs Wu-Xia
        8. Print a summary of input and output file locations

    The Hybrid CSV is read and labelled as "FFR" in all plots because
    the Hybrid series is the FFR-based shock — the label "Hybrid" is
    an internal construction label, not the thesis-facing name.
    """

    # ── Step 1: Locate required IRF CSV files ────────────────────────────────
    # Regex patterns match regardless of exact p and H values in the filename
    ad_pre_path  = find_first(r"Table_IRF_AruobaDrechsel_Pre2008_p\d+_H\d+_EBP\.csv")
    hy_pre_path  = find_first(r"Table_IRF_Hybrid_Pre2008_p\d+_H\d+_EBP\.csv")
    wx_post_path = find_first(r"Table_IRF_WuXia_Post2008_p\d+_H\d+_EBP\.csv")

    # ── Step 2: Read IRF CSV files ────────────────────────────────────────────
    h_ad,  vars_ad,  med_ad,  lo_ad,  hi_ad  = read_irf_csv(ad_pre_path)
    # Hybrid series read here — displayed as "FFR" in all figures
    h_ffr, vars_ffr, med_ffr, lo_ffr, hi_ffr = read_irf_csv(hy_pre_path)
    h_wx,  vars_wx,  med_wx,  lo_wx,  hi_wx  = read_irf_csv(wx_post_path)

    # ── Step 3: Variable intersections for overlay figures ────────────────────
    # Variables present in both series, in PREFERRED_ORDER
    common_vars_pre = [v for v in PREFERRED_ORDER if (v in vars_ad and v in vars_ffr)]

    common_vars_ffr_wx = [v for v in PREFERRED_ORDER if (v in vars_ffr and v in vars_wx)]

    # ── Step 4: Horizon alignment warnings ────────────────────────────────────
    if len(h_ad) != len(h_ffr) or not np.allclose(h_ad, h_ffr):
        print("PRE horizons differ between AD and FFR; using AD horizon for Figure 1.")
    if len(h_ffr) != len(h_wx) or not np.allclose(h_ffr, h_wx):
        print("Horizons differ between PRE FFR and POST Wu-Xia; using PRE horizon for Figure 3.")

    # ── Figure 1: Pre-2008 AD vs FFR (Hybrid labeled as FFR) ─────────────────
    out1 = os.path.join(OUTDIR, "Figure_Pre2008_Compare_AD_vs_FFR.png")
    plot_overlay_two_shocks(
        h_ad,
        common_vars_pre,
        (med_ad,  lo_ad,  hi_ad),
        (med_ffr, lo_ffr, hi_ffr),
        labelA = "AD",
        labelB = "FFR",
        title  = "Pre-2008: IRFs to AD vs FFR Monetary Policy Shocks",
        out_png = out1,
    )

    # ── Figure 2: Post-2008 Wu-Xia only ──────────────────────────────────────
    out2 = os.path.join(OUTDIR, "Figure_Post2008_IRF_WuXia.png")
    # Variables in PREFERRED_ORDER that are present in the Wu-Xia CSV
    vars_wx_plot = [v for v in PREFERRED_ORDER if v in vars_wx] + \
                   [v for v in vars_wx if v not in PREFERRED_ORDER]
    plot_single_shock(
        h_wx,
        vars_wx_plot,
        med_wx, lo_wx, hi_wx,
        title   = "Post-2008: IRFs to Wu-Xia Monetary Policy Shock",
        out_png = out2,
    )

    # ── Figure 3: Cross-regime PRE FFR vs POST Wu-Xia ────────────────────────
    # PRE horizon used by default (consistent with thesis wording)
    out3 = os.path.join(OUTDIR, "Figure_CrossRegime_Compare_PreFFR_vs_PostWuXia.png")
    plot_overlay_two_shocks(
        h_ffr,
        common_vars_ffr_wx,
        (med_ffr, lo_ffr, hi_ffr),
        (med_wx,  lo_wx,  hi_wx),
        labelA  = "FFR (Pre-2008)",
        labelB  = "Wu-Xia (Post-2008)",
        title   = "Cross-regime: Pre-2008 FFR vs Post-2008 Wu-Xia",
        out_png = out3,
    )

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\nDone.")
    print("Inputs:")
    print("  AD PRE  :", ad_pre_path)
    print("  FFR PRE :", hy_pre_path, " (Hybrid series labeled as FFR)")
    print("  WX POST :", wx_post_path)
    print("Outputs saved to:")
    print(" ", OUTDIR)


if __name__ == "__main__":
    main()