"""
================================================================================
robustness_alternative_shocks.py
================================================================================
Thesis:  "When Rates Hit Zero: Identifying Monetary Shocks with Shadow Rates"
Author:  Burak Tanir
Date:    April 2026

Purpose
-------
Produces two robustness figures for Section 6 of the thesis (Alternative
Shock Series) by reading pre-saved IRF CSV tables generated by
bvar_irf_estimation.py. No re-estimation is performed — this script is
purely a plotting tool.

    Figure 1 — Pre-2008: Four-Shock Comparison (Section 6.1)
        Compares median IRFs from four shock series estimated over the
        pre-2008 conventional policy period:
            AD       — original Aruoba-Drechsel (2024) shock
            FFR      — replicated FFR-based (Hybrid) shock
            Wu-Xia   — Wu-Xia (2016) shadow rate shock
        Displays median lines only (no credible bands) to keep the
        four-series comparison uncluttered. Distinct line styles enable
        identification in black-and-white reproduction.

    Figure 2 — Post-2008: Wu-Xia vs Krippner (Section 6.2)
        Compares Wu-Xia and Krippner shadow rate shocks in the post-2008
        zero lower bound period. Displays median lines with 68% credible
        bands for both series. The comparison validates the choice of
        Wu-Xia as the main post-2008 instrument.

Notes on labelling
------------------
    The Hybrid shock CSV is read and displayed as "FFR" in all figures,
    consistent with the convention in thesis_irf_figures.py. "Hybrid"
    is an internal construction label; "FFR" is the thesis-facing name.

Variable ordering and labels
-----------------------------
    All figures follow the PREFERRED_ORDER and DISPLAY_LABELS defined
    in this script, matching thesis_irf_figures.py exactly:
        1. y1         — 1Y Gov Bond (%)
        2. log_sp500  — S&P500 (100 × log)
        3. log_rgdp   — Real GDP (100 × log)
        4. unemp      — Unemployment (%)
        5. log_pgdp   — GDP Deflator (100 × log)
        6. EBP        — EBP (%)

Input
-----
    irf_outputs_EBP_final/
        IRF CSV tables produced by bvar_irf_estimation.py. Files are
        located by regex pattern so exact p and H values do not need
        to be hardcoded:
            Table_IRF_AruobaDrechsel_Pre2008_p{p}_H{H}_EBP.csv
            Table_IRF_Hybrid_Pre2008_p{p}_H{H}_EBP.csv
            Table_IRF_WuXia_Pre2008_p{p}_H{H}_EBP.csv
            Table_IRF_WuXia_Post2008_p{p}_H{H}_EBP.csv
            Table_IRF_Krippner_Post2008_p{p}_H{H}_EBP.csv

Output
------
    irf_outputs_EBP_final/thesis_figures_from_csv/
        Figure_Pre2008_Compare_AD_FFR_WuXia.png
        Figure_Post2008_Compare_WuXia_Krippner.png

    All figures saved at 300 dpi with tight bounding boxes.

Dependencies
------------
    os, re  (standard library)
    numpy, pandas, matplotlib  — pip install numpy pandas matplotlib

Usage
-----
    python robustness_alternative_shocks.py

    Must be run after bvar_irf_estimation.py has produced the IRF CSV
    tables. Run from the same working directory as the estimation script.
================================================================================
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# SECTION 1 — PATH CONFIGURATION
# ============================================================
# IRF CSV tables are read from irf_outputs_EBP_final/ (produced by
# bvar_irf_estimation.py). Both figures are saved to the same
# thesis_figures_from_csv/ subfolder as the preliminary figures.

BASE_DIR = os.getcwd()
IRF_DIR  = os.path.join(BASE_DIR, "irf_outputs_EBP_final")
OUTDIR   = os.path.join(IRF_DIR, "thesis_figures_from_csv")
os.makedirs(OUTDIR, exist_ok=True)


# ============================================================
# SECTION 2 — DISPLAY SETTINGS
# ============================================================
# DISPLAY_LABELS and PREFERRED_ORDER match thesis_irf_figures.py exactly
# so that variable labels and panel positions are consistent across all
# thesis figures.

DISPLAY_LABELS = {
    "y1":        "1Y Gov Bond (%)",
    "log_sp500": "S&P500 (100 × log)",
    "log_rgdp":  "Real GDP (100 × log)",
    "unemp":     "Unemployment (%)",
    "log_pgdp":  "GDP Deflator (100 × log)",
    "EBP":       "EBP (%)",
}

# Fixed variable order — matches macro_vars in bvar_irf_estimation.py
PREFERRED_ORDER = ["y1", "log_sp500", "log_rgdp", "unemp", "log_pgdp", "EBP"]


def pretty_ylabel(varname: str) -> str:
    """Return the thesis-standard y-axis label for a BVAR variable."""
    return DISPLAY_LABELS.get(varname, varname)


# ============================================================
# SECTION 3 — FILE HELPER FUNCTIONS
# ============================================================

def find_first(pattern: str) -> str:
    """
    Find the first file in IRF_DIR whose name fully matches a regex pattern.

    Regex matching makes the script robust to changes in the p (lag order)
    and H (horizon) values baked into the CSV filenames. The first
    alphabetically sorted match is returned.

    Parameters
    ----------
    pattern : str  Full-match regex pattern for the filename.

    Returns
    -------
    str  Absolute path to the matched file.

    Raises
    ------
    FileNotFoundError  If no matching file is found in IRF_DIR.
    """
    rx = re.compile(pattern)
    for fn in sorted(os.listdir(IRF_DIR)):
        if rx.fullmatch(fn):
            return os.path.join(IRF_DIR, fn)
    raise FileNotFoundError(
        f"Could not find a file matching:\n  {pattern}\nIn:\n  {IRF_DIR}"
    )


def read_irf_csv(path: str):
    """
    Read a saved IRF CSV table and return arrays ready for plotting.

    The CSV format has columns:
        h           — horizon index (0, 1, ..., H)
        {var}_med   — posterior median IRF
        {var}_lo    — lower credible band (16th percentile)
        {var}_hi    — upper credible band (84th percentile)

    Variables are returned in PREFERRED_ORDER where available, with any
    additional variables appended at the end.

    Parameters
    ----------
    path : str  Absolute path to the IRF CSV file.

    Returns
    -------
    h            : np.ndarray   Horizon array (H+1,).
    ordered_vars : list of str  Variable names in PREFERRED_ORDER.
    med          : dict         {var: np.ndarray} posterior medians.
    lo           : dict         {var: np.ndarray} lower credible bands.
    hi           : dict         {var: np.ndarray} upper credible bands.

    Raises
    ------
    ValueError  If 'h' or any required _med/_lo/_hi column is missing.
    """
    df = pd.read_csv(path)

    if "h" not in df.columns:
        raise ValueError(f"'h' column missing in {path}. Columns: {list(df.columns)}")

    h = df["h"].to_numpy()

    # Identify variables from columns ending with _med
    vars_found = []
    for c in df.columns:
        if c.endswith("_med"):
            vars_found.append(c[:-4])

    vars_found   = sorted(set(vars_found))
    ordered_vars = [v for v in PREFERRED_ORDER if v in vars_found] + \
                   [v for v in vars_found if v not in PREFERRED_ORDER]

    med, lo, hi = {}, {}, {}
    for v in ordered_vars:
        med_col = f"{v}_med"
        lo_col  = f"{v}_lo"
        hi_col  = f"{v}_hi"

        if med_col not in df.columns or lo_col not in df.columns or hi_col not in df.columns:
            raise ValueError(
                f"Missing one of {med_col}, {lo_col}, {hi_col} in {path}"
            )

        med[v] = df[med_col].to_numpy()
        lo[v]  = df[lo_col].to_numpy()
        hi[v]  = df[hi_col].to_numpy()

    return h, ordered_vars, med, lo, hi


# ============================================================
# SECTION 4 — PLOTTING FUNCTIONS
# ============================================================

def plot_four_shock_pre_comparison(h, vars_list, irf_dict, title, out_png):
    """
    Plot median IRFs from four pre-2008 shock series in the same panels.

    Displays median lines only (no credible bands) to keep the four-series
    comparison visually uncluttered. Each series receives a distinct line
    style for identification in black-and-white reproduction.

    Used for Figure 1 (Section 6.1): pre-2008 four-shock comparison.

    Parameters
    ----------
    h         : np.ndarray   Horizon array.
    vars_list : list of str  Variables to plot (in PREFERRED_ORDER).
    irf_dict  : dict         {label: (med, lo, hi)} for each shock series.
                             Keys must be: "AD", "FFR", "Wu-Xia".
    title     : str          Figure suptitle.
    out_png   : str          Output PNG file path.
    """
    n     = len(vars_list)
    nrows = int(np.ceil(n / 2))
    fig, axes = plt.subplots(nrows, 2, figsize=(12, 4 * nrows), sharex=True)
    axes = np.array(axes).reshape(-1)

    # Distinct line styles — distinguishable in greyscale
    line_styles = {
        "AD":       "-",
        "FFR":      "--",
        "Wu-Xia":   ":",
    }

    SCALE_BY_100 = ["log_sp500", "log_rgdp", "log_pgdp"]

    for i, v in enumerate(vars_list):
        ax = axes[i]
        sc = 100.0 if v in SCALE_BY_100 else 1.0

        for label, (med, _, _) in irf_dict.items():
            ax.plot(
                h,
                sc * med[v],
                linewidth=2,
                linestyle=line_styles.get(label, "-"),
                label=label
            )

        ax.axhline(0, linewidth=1)
        ax.set_ylabel(pretty_ylabel(v))
        ax.grid(True)
        ax.legend()

    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(title, y=1.02, fontsize=14)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.show()
    print(f"Saved: {out_png}")


def plot_two_shock_post_comparison(h, vars_list, irf_dict, title, out_png):
    """
    Plot two post-2008 shadow rate IRF sets with 68% credible bands.

    Displays posterior median lines with 68% credible bands (15% opacity)
    for both Wu-Xia and Krippner series. Each series has a distinct colour
    and line style.

    Used for Figure 2 (Section 6.2): post-2008 Wu-Xia vs Krippner.

    Parameters
    ----------
    h         : np.ndarray   Horizon array.
    vars_list : list of str  Variables to plot (in PREFERRED_ORDER).
    irf_dict  : dict         {label: (med, lo, hi)} for each shock series.
                             Keys must be: "Wu-Xia", "Krippner".
    title     : str          Figure suptitle.
    out_png   : str          Output PNG file path.
    """
    # Colour and line style scheme — distinguishable in greyscale
    styles = {
        "Wu-Xia":   dict(color="#2ca02c", ls=":",  lw=2.2),
        "Krippner": dict(color="#d62728", ls="-.", lw=2.2),
    }

    n     = len(vars_list)
    nrows = int(np.ceil(n / 2))
    fig, axes = plt.subplots(nrows, 2,
                             figsize=(12, 4 * nrows),
                             sharex=True)
    axes = np.array(axes).reshape(-1)

    SCALE_BY_100 = ["log_sp500", "log_rgdp", "log_pgdp"]

    for i, v in enumerate(vars_list):
        ax = axes[i]
        sc = 100.0 if v in SCALE_BY_100 else 1.0

        for label, (med, lo, hi) in irf_dict.items():
            st = styles[label]
            ax.plot(h, sc * med[v], label=label,
                    color=st["color"], ls=st["ls"], lw=st["lw"])
            ax.fill_between(h, sc * lo[v], sc * hi[v],
                            color=st["color"], alpha=0.15)

        ax.axhline(0, color="steelblue", linewidth=0.9)
        ax.set_ylabel(pretty_ylabel(v))
        ax.set_title(v, fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8, loc="best")

    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(title, y=1.02, fontsize=13)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.show()
    print(f"Saved: {out_png}")


# ============================================================
# SECTION 5 — MAIN EXECUTION
# ============================================================

def main():
    """
    Main execution function: produce both robustness figures.

    Execution order:
        1.  Locate six IRF CSV files by regex pattern
        2.  Read all six CSVs into horizon arrays and IRF dictionaries
        3.  Compute common variable sets using PREFERRED_ORDER
        4.  Validate horizon consistency across files
        5.  Produce Figure 1: Pre-2008 four-shock comparison
        6.  Produce Figure 2: Post-2008 Wu-Xia vs Krippner
        7.  Print input and output file summary

    The Hybrid CSV is read and passed as "FFR" in Figure 1 because the
    Hybrid series is the FFR-based shock — "Hybrid" is an internal label.
    """

    # ── Step 1: Locate all required IRF CSV files ─────────────────────────────
    # Regex patterns match regardless of exact p and H values in filename
    ad_pre_path  = find_first(r"Table_IRF_AruobaDrechsel_Pre2008_p\d+_H\d+_EBP\.csv")
    ffr_pre_path = find_first(r"Table_IRF_Hybrid_Pre2008_p\d+_H\d+_EBP\.csv")   # displayed as FFR
    wx_pre_path  = find_first(r"Table_IRF_WuXia_Pre2008_p\d+_H\d+_EBP\.csv")
    wx_post_path = find_first(r"Table_IRF_WuXia_Post2008_p\d+_H\d+_EBP\.csv")
    kr_post_path = find_first(r"Table_IRF_Krippner_Post2008_p\d+_H\d+_EBP\.csv")

    # ── Step 2: Read all six CSVs ─────────────────────────────────────────────
    h_ad,  vars_ad,  med_ad,  lo_ad,  hi_ad  = read_irf_csv(ad_pre_path)
    h_ffr, vars_ffr, med_ffr, lo_ffr, hi_ffr = read_irf_csv(ffr_pre_path)
    h_wx,  vars_wx,  med_wx,  lo_wx,  hi_wx  = read_irf_csv(wx_pre_path)

    h_wx_post, vars_wx_post, med_wx_post, lo_wx_post, hi_wx_post = read_irf_csv(wx_post_path)
    h_kr_post, vars_kr_post, med_kr_post, lo_kr_post, hi_kr_post = read_irf_csv(kr_post_path)

    # ── Step 3: Common variable sets in PREFERRED_ORDER ───────────────────────
    # Pre-2008: variables present in all four series
    common_vars_pre = [
        v for v in PREFERRED_ORDER
        if (v in vars_ad and v in vars_ffr and v in vars_wx)
    ]
    if not common_vars_pre:
        common_vars_pre = sorted(
            set(vars_ad).intersection(vars_ffr).intersection(vars_wx)
        )
    if not common_vars_pre:
        raise ValueError("No common variables found across AD, FFR, and Wu-Xia CSVs.")

    # Post-2008: variables present in both series
    common_vars_post = [
        v for v in PREFERRED_ORDER
        if v in vars_wx_post and v in vars_kr_post
    ]
    if not common_vars_post:
        common_vars_post = sorted(set(vars_wx_post).intersection(vars_kr_post))
    if not common_vars_post:
        raise ValueError("No common variables found across Wu-Xia and Krippner post-2008 CSVs.")

    # ── Step 4: Horizon consistency checks ────────────────────────────────────
    if not (len(h_ad) == len(h_ffr) == len(h_wx)):
        raise ValueError("IRF horizons differ across the three pre-2008 CSV files.")
    if not (np.allclose(h_ad, h_ffr) and np.allclose(h_ad, h_wx)):
        raise ValueError("IRF horizon values differ across the three pre-2008 CSV files.")

    if len(h_wx_post) != len(h_kr_post):
        raise ValueError("IRF horizons differ between Wu-Xia and Krippner post-2008 CSVs.")
    if not np.allclose(h_wx_post, h_kr_post):
        raise ValueError("IRF horizon values differ between Wu-Xia and Krippner post-2008 CSVs.")

    h_pre  = h_ad
    h_post = h_wx_post

    # ── Figure 1: Pre-2008 four-shock comparison ──────────────────────────────
    out_png_pre = os.path.join(
        OUTDIR,
        "Figure_Pre2008_Compare_AD_FFR_WuXia.png"
    )

    plot_four_shock_pre_comparison(
        h         = h_pre,
        vars_list = common_vars_pre,
        irf_dict  = {
            "AD":       (med_ad,  lo_ad,  hi_ad),
            "FFR":      (med_ffr, lo_ffr, hi_ffr),
            "Wu-Xia":   (med_wx,  lo_wx,  hi_wx),
        },
        title   = "Pre-2008: Comparison of IRFs to AD, FFR, and Wu-Xia Monetary Policy Shocks",
        out_png = out_png_pre,
    )

    # ── Figure 2: Post-2008 Wu-Xia vs Krippner ───────────────────────────────
    out_png_post = os.path.join(
        OUTDIR,
        "Figure_Post2008_Compare_WuXia_Krippner.png"
    )

    plot_two_shock_post_comparison(
        h         = h_post,
        vars_list = common_vars_post,
        irf_dict  = {
            "Wu-Xia":   (med_wx_post, lo_wx_post, hi_wx_post),
            "Krippner": (med_kr_post, lo_kr_post, hi_kr_post),
        },
        title   = (
            "Post-2008: Comparison of IRFs to Wu-Xia and Krippner "
            "Shadow Rate Monetary Policy Shocks\n"
            "ZLB Period | Median IRFs with 68% credible intervals"
        ),
        out_png = out_png_post,
    )

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\nDone.")
    print("Inputs (pre-2008):")
    print("  AD       :", ad_pre_path)
    print("  FFR      :", ffr_pre_path, " (Hybrid CSV displayed as FFR)")
    print("  Wu-Xia   :", wx_pre_path)
    print("Inputs (post-2008):")
    print("  Wu-Xia   :", wx_post_path)
    print("  Krippner :", kr_post_path)
    print("Outputs:")
    print(" ", out_png_pre)
    print(" ", out_png_post)


if __name__ == "__main__":
    main()