"""
================================================================================
lp_thesis_figures.py
================================================================================
Thesis:  "When Rates Hit Zero: Identifying Monetary Shocks with Shadow Rates"
Author:  Burak Tanir
Date:    April 2026

Purpose
-------
Produces the two thesis-ready Local Projection (LP) figures reported in
Section 7 of the thesis by reading pre-saved LP coefficient CSV tables
generated by lp_results.py. No re-estimation is performed — this script
is a publication-quality plotting tool only.

    Figure LP-1 — Pre-2008: AD vs FFR Comparison (Section 7.1)
        Compares LP impulse responses from two shock series estimated
        over the pre-2008 (conventional policy) period:
            AD  — original Aruoba-Drechsel (2024) shock
            FFR — replicated FFR-based (Hybrid) shock
        Each series is shown with its ±1 Newey-West HAC standard error band.
        Panel layout, variable ordering, and colour scheme match the BVAR
        pre-2008 validation figures exactly.

    Figure LP-2 — Post-2008: Wu-Xia (Section 7.2)
        Shows LP impulse responses to the Wu-Xia shadow rate shock over
        the post-2008 (zero lower bound) period with ±1 HAC standard error
        band. Directly comparable to the post-2008 BVAR results.

Notes on labelling
------------------
    The Hybrid CSV (lp_HYBRID_PRE.csv) is read and displayed as "FFR"
    in Figure LP-1, consistent with all other thesis figures.

Variable ordering and labels
-----------------------------
    All figures use the same PREFERRED_ORDER and PANEL_LABELS as the
    BVAR thesis figures (thesis_irf_figures.py):
        1. y1         — 1Y Gov Bond (%)
        2. log_sp500  — S&P500 (100 × log)
        3. log_rgdp   — Real GDP (100 × log)
        4. unemp      — Unemployment (%)
        5. log_pgdp   — GDP Deflator (100 × log)
        6. EBP        — EBP (%)

    Log variables (log_sp500, log_rgdp, log_pgdp) are multiplied by 100
    before plotting so that units match the BVAR figures.

Input
-----
    lp_outputs_EBP_linear/
        lp_AD_PRE.csv       — AD pre-2008 LP coefficients
        lp_HYBRID_PRE.csv   — Hybrid (FFR) pre-2008 LP coefficients
        lp_WX_POST.csv      — Wu-Xia post-2008 LP coefficients

    CSV format per file:
        h           — horizon index (0, 1, ..., H)
        {var}_b     — OLS coefficient (impulse response)
        {var}_lo    — lower band (b − 1 HAC SE)
        {var}_hi    — upper band (b + 1 HAC SE)

Output
------
    lp_outputs_EBP_linear/thesis_figures/
        LP_Figure1_Pre2008_FourShock.png
        LP_Figure2_Post2008_WX_vs_KR.png

    Both figures saved at 300 dpi with tight bounding boxes.

Dependencies
------------
    os, re  (standard library)
    numpy, pandas, matplotlib  — pip install numpy pandas matplotlib

Usage
-----
    python lp_thesis_figures.py

    Must be run after lp_results.py has produced the LP CSV tables.
    Run from the same working directory as lp_results.py.
================================================================================
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib import rcParams


# ============================================================
# SECTION 1 — PATH CONFIGURATION
# ============================================================
# LP CSV tables are read from lp_outputs_EBP_linear/ (produced by
# lp_results.py). Both thesis figures are saved to a dedicated
# subfolder to keep them separate from the raw LP outputs.

BASE_DIR = os.getcwd()
LP_DIR   = os.path.join(BASE_DIR, "lp_outputs_EBP_linear")
OUTDIR   = os.path.join(LP_DIR, "thesis_figures")
os.makedirs(OUTDIR, exist_ok=True)


# ============================================================
# SECTION 2 — VARIABLE ORDER AND PANEL LABELS
# ============================================================
# VAR_ORDER and PANEL_LABELS match thesis_irf_figures.py exactly so
# that the same variable always occupies the same panel position across
# all BVAR and LP figures in the thesis.

# Fixed variable order — matches PREFERRED_ORDER in thesis_irf_figures.py
# and macro_vars in bvar_irf_estimation.py
VAR_ORDER = ["y1", "log_sp500", "log_rgdp", "unemp", "log_pgdp", "EBP"]

# Thesis-standard panel labels — matching DISPLAY_LABELS in thesis_irf_figures.py
PANEL_LABELS = {
    "y1":        "1Y Gov Bond (%)",
    "log_sp500": "S&P500 (100 × log)",
    "log_rgdp":  "Real GDP (100 × log)",
    "unemp":     "Unemployment (%)",
    "log_pgdp":  "GDP Deflator (100 × log)",
    "EBP":       "EBP (%)",
}

# Log variables multiplied by 100 before plotting to match BVAR figure units
SCALE_BY_100 = ["log_sp500", "log_rgdp", "log_pgdp"]


# ============================================================
# SECTION 3 — TYPOGRAPHY AND STYLE
# ============================================================
# Serif font and clean spine settings for publication-quality output.

rcParams["font.family"]      = "serif"
rcParams["font.serif"]       = ["Times New Roman", "Times", "DejaVu Serif"]
rcParams["mathtext.fontset"] = "stix"
rcParams["axes.spines.top"]  = False
rcParams["axes.spines.right"]= False


# ============================================================
# SECTION 4 — COLOUR AND LINE PALETTE
# ============================================================
# Colours and line styles match the BVAR sample-controlled comparison
# figures exactly, enabling direct visual comparison between the BVAR
# and LP robustness results.

# Figure LP-1: four pre-2008 shock series
STYLES_PRE = {
    "AD":  dict(color="#1f77b4", ls="-",  lw=2.0, zorder=4),  # blue   — solid
    "FFR": dict(color="#ff7f0e", ls="--", lw=2.0, zorder=3),  # orange — dashed
}
FILL_ALPHA_PRE = 0.12

# Figure LP-2: two post-2008 shadow rate series
STYLES_POST = {
    "Wu-Xia": dict(color="#2ca02c", ls="-", lw=2.0, zorder=3),  # green — solid
}
FILL_ALPHA_POST = 0.12


# ============================================================
# SECTION 5 — HELPER FUNCTIONS
# ============================================================

def read_lp_csv(path: str) -> pd.DataFrame:
    """
    Read an LP coefficient CSV produced by lp_results.py.

    Raises FileNotFoundError with the full path if the file is missing,
    allowing the user to immediately identify which LP run is needed.

    Parameters
    ----------
    path : str  Absolute path to the LP CSV file.

    Returns
    -------
    pd.DataFrame  CSV contents with columns h, {var}_b, {var}_lo, {var}_hi.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"LP CSV not found:\n  {path}")
    return pd.read_csv(path)


def get_arrays(df: pd.DataFrame, var: str):
    """
    Extract horizon and IRF arrays for one variable from an LP CSV.

    Applies the ×100 scaling factor for log variables so that plotted
    values match the thesis unit convention (100 × log).

    Parameters
    ----------
    df  : pd.DataFrame  LP coefficient CSV loaded by read_lp_csv().
    var : str           Variable name (e.g. 'y1', 'log_rgdp').

    Returns
    -------
    h  : np.ndarray  Horizon array.
    b  : np.ndarray  OLS coefficient (possibly scaled by 100).
    lo : np.ndarray  Lower band (b − 1 HAC SE, possibly scaled).
    hi : np.ndarray  Upper band (b + 1 HAC SE, possibly scaled).
    """
    h  = df["h"].to_numpy()
    sc = 100.0 if var in SCALE_BY_100 else 1.0
    b  = sc * df[f"{var}_b"].to_numpy()
    lo = sc * df[f"{var}_lo"].to_numpy()
    hi = sc * df[f"{var}_hi"].to_numpy()
    return h, b, lo, hi


def find_csv(directory: str, pattern: str) -> str:
    """
    Find the first file in directory whose name fully matches a regex pattern.

    Case-insensitive matching allows the function to handle minor
    capitalisation differences in filenames.

    Parameters
    ----------
    directory : str  Folder to search.
    pattern   : str  Full-match regex pattern for the filename.

    Returns
    -------
    str  Absolute path to the matched file.

    Raises
    ------
    FileNotFoundError  If no matching file is found.
    """
    rx = re.compile(pattern, re.IGNORECASE)
    for fn in sorted(os.listdir(directory)):
        if rx.fullmatch(fn):
            return os.path.join(directory, fn)
    raise FileNotFoundError(
        f"No file matching '{pattern}' in:\n  {directory}"
    )


def add_panel_label(ax, letter, x=-0.12, y=1.05):
    """
    Add a bold alphabetic panel label (A, B, C, ...) to a subplot axis.

    Placed in the upper-left corner outside the plot area, following
    the convention used in academic journal figures.

    Parameters
    ----------
    ax     : matplotlib Axes  Target subplot.
    letter : str              Single uppercase letter label.
    x, y   : float            Position in axes coordinates.
    """
    ax.text(x, y, letter, transform=ax.transAxes,
            fontsize=10, fontweight="bold",
            va="top", ha="left", fontfamily="serif")


def format_ax(ax, ylabel, show_xlabel=False):
    """
    Apply consistent formatting to a single IRF panel.

    Sets a light horizontal zero line, y-axis label, tick formatting,
    and optional x-axis label. Removes the top and right spines via
    rcParams (already set at module level).

    Parameters
    ----------
    ax          : matplotlib Axes  Target subplot.
    ylabel      : str              Y-axis label from PANEL_LABELS.
    show_xlabel : bool             Whether to add 'Months after shock' label.
    """
    ax.axhline(0, color="#999999", lw=0.8, ls="-", zorder=0)
    ax.set_ylabel(ylabel, fontsize=8.5, labelpad=4)
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%.4g"))
    ax.tick_params(axis="both", labelsize=8)
    ax.grid(axis="y", alpha=0.25, lw=0.6)
    if show_xlabel:
        ax.set_xlabel("Months after shock", fontsize=8.5)


# ============================================================
# SECTION 6 — FIGURE LP-1: PRE-2008 FOUR-SHOCK COMPARISON
# ============================================================

def make_figure_pre(out_png: str):
    """
    Produce Figure LP-1: pre-2008 four-shock LP comparison.

    Reads LP coefficient CSVs for AD and FFR (Hybrid) over the pre-2008
    period. Plots median LP coefficients with ±1 HAC standard error bands
    for both series in a two-column panel grid.
    Legend is placed in panel A (upper left panel) only.

    The Hybrid CSV is read and labelled "FFR" — consistent with all other
    thesis figures.

    Parameters
    ----------
    out_png : str  Output PNG file path.
    """
    # Load pre-2008 LP CSV tables (AD and FFR only)
    df_ad  = read_lp_csv(find_csv(LP_DIR, r"lp_AD_PRE\.csv"))
    df_ffr = read_lp_csv(find_csv(LP_DIR, r"lp_HYBRID_PRE\.csv"))

    # Hybrid CSV displayed as "FFR"
    data = {
        "AD":  df_ad,
        "FFR": df_ffr,
    }

    # Retain only variables present in all four CSVs, in VAR_ORDER
    available = [v for v in VAR_ORDER
                 if all(f"{v}_b" in df.columns for df in data.values())]

    n     = len(available)
    ncols = 2
    nrows = int(np.ceil(n / ncols))

    fig, axes = plt.subplots(
        nrows, ncols,
        figsize=(6.5 * ncols, 3.2 * nrows),
        sharex=True,
        constrained_layout=True,
    )
    axes = np.array(axes).reshape(-1)

    panel_letters = "ABCDEF"

    for i, var in enumerate(available):
        ax     = axes[i]
        show_x = (i >= n - ncols)   # show x-axis label on bottom row only

        for label, df in data.items():
            h, b, lo, hi = get_arrays(df, var)
            st = STYLES_PRE[label]
            ax.plot(h, b, label=label,
                    color=st["color"], ls=st["ls"],
                    lw=st["lw"], zorder=st["zorder"])
            ax.fill_between(h, lo, hi,
                            color=st["color"],
                            alpha=FILL_ALPHA_PRE,
                            zorder=st["zorder"] - 1)

        format_ax(ax, PANEL_LABELS.get(var, var), show_xlabel=show_x)
        add_panel_label(ax, panel_letters[i])

        # Legend in panel A only to avoid repetition
        if i == 0:
            ax.legend(
                fontsize=8, framealpha=0.9,
                edgecolor="#cccccc", loc="upper right",
                handlelength=2.2, labelspacing=0.3,
            )

    # Turn off unused panels
    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(
        "Pre-2008 Local Projection Impulse Responses\n"
        "AD and FFR Monetary Policy Shocks  "
        r"$\pm$1 S.E. bands  |  Newey-West HAC",
        fontsize=10, y=1.01, ha="center",
    )

    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved Figure LP-1 → {out_png}")


# ============================================================
# SECTION 7 — FIGURE LP-2: POST-2008 WU-XIA VS KRIPPNER
# ============================================================

def make_figure_post(out_png: str):
    """
    Produce Figure LP-2: post-2008 Wu-Xia vs Krippner LP comparison.

    Reads the post-2008 LP coefficient CSV for Wu-Xia only.
    Plots median LP coefficients with ±1 HAC standard error band.
    Legend placed in panel A only.

    Parameters
    ----------
    out_png : str  Output PNG file path.
    """
    # Load post-2008 LP CSV table (Wu-Xia only)
    df_wx = read_lp_csv(find_csv(LP_DIR, r"lp_WX_POST\.csv"))

    data = {
        "Wu-Xia": df_wx,
    }

    # Retain only variables present in both CSVs, in VAR_ORDER
    available = [v for v in VAR_ORDER
                 if all(f"{v}_b" in df.columns for df in data.values())]

    n     = len(available)
    ncols = 2
    nrows = int(np.ceil(n / ncols))

    fig, axes = plt.subplots(
        nrows, ncols,
        figsize=(6.5 * ncols, 3.2 * nrows),
        sharex=True,
        constrained_layout=True,
    )
    axes = np.array(axes).reshape(-1)

    panel_letters = "ABCDEF"

    for i, var in enumerate(available):
        ax     = axes[i]
        show_x = (i >= n - ncols)

        for label, df in data.items():
            h, b, lo, hi = get_arrays(df, var)
            st = STYLES_POST[label]
            ax.plot(h, b, label=label,
                    color=st["color"], ls=st["ls"],
                    lw=st["lw"], zorder=st["zorder"])
            ax.fill_between(h, lo, hi,
                            color=st["color"],
                            alpha=FILL_ALPHA_POST,
                            zorder=st["zorder"] - 1)

        format_ax(ax, PANEL_LABELS.get(var, var), show_xlabel=show_x)
        add_panel_label(ax, panel_letters[i])

        # Legend in panel A only
        if i == 0:
            ax.legend(
                fontsize=8, framealpha=0.9,
                edgecolor="#cccccc", loc="upper right",
                handlelength=2.2, labelspacing=0.3,
            )

    for k in range(n, len(axes)):
        axes[k].axis("off")

    fig.suptitle(
        "Post-2008 Local Projection Impulse Responses\n"
        "Wu-Xia Shadow Rate Shock  "
        r"$\pm$1 S.E. bands  |  Newey-West HAC  |  ZLB Period",
        fontsize=10, y=1.01, ha="center",
    )

    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved Figure LP-2 → {out_png}")


# ============================================================
# SECTION 8 — MAIN EXECUTION
# ============================================================

def main():
    """
    Main execution function: produce both LP thesis figures.

    Execution order:
        1. Produce Figure LP-1: pre-2008 AD vs FFR comparison
        2. Produce Figure LP-2: post-2008 Wu-Xia only
        3. Print output folder location
    """
    out1 = os.path.join(OUTDIR, "LP_Figure1_Pre2008_FourShock.png")
    out2 = os.path.join(OUTDIR, "LP_Figure2_Post2008_WX_vs_KR.png")

    print("Generating Figure LP-1 — Pre-2008 AD vs FFR comparison...")
    make_figure_pre(out1)

    print("Generating Figure LP-2 — Post-2008 Wu-Xia only...")
    make_figure_post(out2)

    print("\nDone. Figures saved in:")
    print(f"   {OUTDIR}")


if __name__ == "__main__":
    main()